@startuml
title 基于GitHub的实验管理平台--查看成绩用例的顺序图
actor teachers
teachers -> grades: 查看成绩和评语
grades -> tests
tests --> teachers:不同班级所有同学的每个实验的信息、成绩和评语

actor students
students -> grades: 查看成绩和评语
grades -> tests
tests --> students:不同课程每个实验的信息、成绩和评语
@enduml